sudo: required
language: python
python:
  - "3.5"
services:
  - docker
install:
  - docker-compose -f dev.yml build  # se construye nuevamente la imagen con tu nuevo feature
  - docker-compose -f dev.yml run --no-deps backend python test.pys

before_script:
  - pip install mock


script:
  - docker ps | grep -q flask_restaurant

